#ifndef POKEDEX_HPP
#define POKEDEX_HPP

#include "Type.hpp"
#include <string>

typedef uint32_t ID;
typedef std::string Name;

class PokedexEntry
{
    const ID dex;
    const Name name;
    const PokemonType type;

public:
    PokedexEntry(ID dex, Name name, PokemonType type) : dex(dex), name(name), type(type) {}
};

class Pokedex
{
    const PokedexEntry pokemon[151] = {
        PokedexEntry(1, "Bulbasaur", PokemonType(Type::Grass, Type::Poison)),
        PokedexEntry(2, "Ivysaur", PokemonType(Type::Grass, Type::Poison)),
        PokedexEntry(3, "Venusaur", PokemonType(Type::Grass, Type::Poison)),
        PokedexEntry(4, "Charmander", PokemonType(Type::Fire)),
        PokedexEntry(5, "Charmeleon", PokemonType(Type::Fire)),
        PokedexEntry(6, "Charizard", PokemonType(Type::Fire, Type::Flying)),
        PokedexEntry(7, "Squirtle", PokemonType(Type::Water)),
        PokedexEntry(8, "Wartortle", PokemonType(Type::Water)),
        PokedexEntry(9, "Blastoise", PokemonType(Type::Water)),
        PokedexEntry(10, "Caterpie", PokemonType(Type::Bug)),
        PokedexEntry(11, "Metapod", PokemonType(Type::Bug)),
        PokedexEntry(12, "Butterfree", PokemonType(Type::Bug,Type::Flying)),
        PokedexEntry(13, "Weedle", PokemonType(Type::Bug,Type::Poison)),
        PokedexEntry(14, "Kakuna", PokemonType(Type::Bug,Type::Poison)),
        PokedexEntry(15, "Beedrill", PokemonType(Type::Bug,Type::Poison)),
        PokedexEntry(16, "Pidgey", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(17, "Pidgeotto", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(18, "Pidgeot", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(19, "Rattatta", PokemonType(Type::Normal)),
        PokedexEntry(20, "Raticate", PokemonType(Type::Normal)),
        PokedexEntry(21, "Spearow", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(22, "Fearow", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(23, "Ekans", PokemonType(Type::Poison)),
        PokedexEntry(24, "Arbok", PokemonType(Type::Poison)),
        PokedexEntry(25, "Pikachu", PokemonType(Type::Electric)),
        PokedexEntry(26, "Raichu", PokemonType(Type::Electric)),
        PokedexEntry(27, "Sandshrew", PokemonType(Type::Ground)),
        PokedexEntry(28, "Sandslash", PokemonType(Type::Ground)),
        PokedexEntry(29, "Nidoran♀", PokemonType(Type::Poison)),
        PokedexEntry(30, "Nidorina", PokemonType(Type::Poison)),
        PokedexEntry(31, "Nidoqueen", PokemonType(Type::Poison,Type::Ground)),
        PokedexEntry(32, "Nidoran♂", PokemonType(Type::Poison)),
        PokedexEntry(33, "Nidorino", PokemonType(Type::Poison)),
        PokedexEntry(34, "Nidoking", PokemonType(Type::Poison,Type::Ground)),
        PokedexEntry(35, "Clefairy", PokemonType(Type::Normal)),
        PokedexEntry(36, "Clefable", PokemonType(Type::Normal)),
        PokedexEntry(37, "Vulpix", PokemonType(Type::Fire)),
        PokedexEntry(38, "Ninetales", PokemonType(Type::Fire)),
        PokedexEntry(39, "Jigglypuff", PokemonType(Type::Normal)),
        PokedexEntry(40, "Wigglytuff", PokemonType(Type::Normal)),
        PokedexEntry(41, "Zubat", PokemonType(Type::Poison,Type::Flying)),
        PokedexEntry(42, "Golbat", PokemonType(Type::Poison,Type::Flying)),
        PokedexEntry(43, "Oddish", PokemonType((Type::Grass,Type::Poison))),
        PokedexEntry(44, "Gloom", PokemonType(Type::Grass,Type::Poison)),
        PokedexEntry(45, "Vileplume", PokemonType(Type::Grass,Type::Poison)),
        PokedexEntry(46, "Paras", PokemonType(Type::Bug,Type::Grass)),
        PokedexEntry(47, "Parasect", PokemonType(Type::Bug,Type::Grass)),
        PokedexEntry(48, "Venonat", PokemonType(Type::Bug,Type::Poison)),
        PokedexEntry(49, "Venomoth", PokemonType(Type::Bug,Type::Poison)),
        PokedexEntry(50, "Diglett", PokemonType(Type::Ground)),
        PokedexEntry(51, "Dugtrio", PokemonType(Type::Ground)),
        PokedexEntry(52, "Meowth", PokemonType(Type::Normal)),
        PokedexEntry(53, "Persian", PokemonType(Type::Normal)),
        PokedexEntry(54, "Psyduck", PokemonType(Type::Water)),
        PokedexEntry(55, "Golduck", PokemonType(Type::Water)),
        PokedexEntry(56, "Mankey", PokemonType(Type::Fighting)),
        PokedexEntry(57, "Primeape", PokemonType(Type::Fighting)),
        PokedexEntry(58, "Growlithe", PokemonType(Type::Fire)),
        PokedexEntry(59, "Arcanine", PokemonType(Type::Fire)),
        PokedexEntry(60, "Poliwag", PokemonType(Type::Water)),
        PokedexEntry(61, "Poliwhirl", PokemonType(Type::Water)),
        PokedexEntry(62, "Poliwrath", PokemonType(Type::Water,Type::Fighting)),
        PokedexEntry(63, "Abra", PokemonType(Type::Psychic)),
        PokedexEntry(64, "Kadabra", PokemonType(Type::Psychic)),
        PokedexEntry(65, "Alakazam", PokemonType(Type::Psychic)),
        PokedexEntry(66, "Machop", PokemonType(Type::Fighting)),
        PokedexEntry(67, "Machoke", PokemonType(Type::Fighting)),
        PokedexEntry(68, "Machamp", PokemonType(Type::Fighting)),
        PokedexEntry(69, "Bellsprout", PokemonType(Type::Grass,Type::Poison)),
        PokedexEntry(70, "Weepinbell", PokemonType(Type::Grass,Type::Poison)),
        PokedexEntry(71, "Victreebel", PokemonType(Type::Grass,Type::Poison)),
        PokedexEntry(72, "Tentacool", PokemonType(Type::Water,Type::Poison)),
        PokedexEntry(73, "Tentacruel", PokemonType(Type::Water,Type::Poison)),
        PokedexEntry(74, "Geodude", PokemonType(Type::Rock,Type::Ground)),
        PokedexEntry(75, "Graveler", PokemonType(Type::Rock,Type::Ground)),
        PokedexEntry(76, "Golem", PokemonType(Type::Rock,Type::Ground)),
        PokedexEntry(77, "Ponyta", PokemonType(Type::Fire)),
        PokedexEntry(78, "Rapidash", PokemonType(Type::Fire)),
        PokedexEntry(79, "Slowpoke", PokemonType(Type::Water,Type::Psychic)),
        PokedexEntry(80, "Slowbro", PokemonType(Type::Water,Type::Psychic)),
        PokedexEntry(81, "Magnemite", PokemonType(Type::Electric)),
        PokedexEntry(82, "Magneton", PokemonType(Type::Electric)),
        PokedexEntry(83, "Farfetch'd", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(84, "Doduo", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(85, "Dodrio", PokemonType(Type::Normal,Type::Flying)),
        PokedexEntry(86, "Seel", PokemonType(Type::Water)),
        PokedexEntry(87, "Dewgong", PokemonType(Type::Water,Type::Ice)),
        PokedexEntry(88, "Grimer", PokemonType(Type::Poison)),
        PokedexEntry(89, "Muk", PokemonType(Type::Poison)),
        PokedexEntry(90, "Shellder", PokemonType(Type::Water)),
        PokedexEntry(91, "Cloyster", PokemonType(Type::Water,Type::Ice)),
        PokedexEntry(92, "Gastly", PokemonType(Type::Ghost,Type::Poison)),
        PokedexEntry(93, "Haunter", PokemonType(Type::Ghost,Type::Poison)),
        PokedexEntry(94, "Gengar", PokemonType(Type::Ghost,Type::Poison)),
        PokedexEntry(95, "Onix", PokemonType(Type::Rock,Type::Ground)),
        PokedexEntry(96, "Drowzee", PokemonType(Type::Psychic)),
        PokedexEntry(97, "Hypno", PokemonType(Type::Psychic)),
        PokedexEntry(98, "Krabby", PokemonType(Type::Water)),
        PokedexEntry(99, "Kingler", PokemonType(Type::Water)),
        PokedexEntry(100, "Voltorb", PokemonType(Type::Electric)),
        PokedexEntry(101, "Electrode", PokemonType(Type::Electric)),
        PokedexEntry(102, "Exeggcute", PokemonType(Type::Grass,Type::Psychic)),
        PokedexEntry(103, "Exeggutor", PokemonType(Type::Grass,Type::Psychic)),
        PokedexEntry(104, "Cubone", PokemonType(Type::Ground)),
        PokedexEntry(105, "Marowak", PokemonType(Type::Ground)),
        PokedexEntry(106, "Hitmonlee", PokemonType(Type::Fighting)),
        PokedexEntry(107, "Hitmonchan", PokemonType(Type::Fighting)),
        PokedexEntry(108, "Lickitung", PokemonType(Type::Normal)),
        PokedexEntry(109, "Koffing", PokemonType(Type::Poison)),
        PokedexEntry(110, "Weezing", PokemonType(Type::Poison)),
        PokedexEntry(111, "Rhyhorn", PokemonType(Type::Ground,Type::Rock)),
        PokedexEntry(112, "Rhydon", PokemonType(Type::Ground,Type::Rock)),
        PokedexEntry(113, "Chansey", PokemonType(Type::Normal)),
        PokedexEntry(114, "Tangela", PokemonType(Type::Grass)),
        PokedexEntry(115, "Kangaskhan", PokemonType(Type::Normal)),
        PokedexEntry(116, "Horsea", PokemonType(Type::Water)),
        PokedexEntry(117, "Seadra", PokemonType(Type::Water)),
        PokedexEntry(118, "Goldeen", PokemonType(Type::Water)),
        PokedexEntry(119, "Seaking", PokemonType(Type::Water)),
        PokedexEntry(120, "Staryu", PokemonType(Type::Water)),
        PokedexEntry(121, "Starmie", PokemonType(Type::Water,Type::Psychic)),
        PokedexEntry(122, "Mr. Mime", PokemonType(Type::Psychic)),
        PokedexEntry(123, "Scyther", PokemonType(Type::Bug,Type::Flying)),
        PokedexEntry(124, "Jynx", PokemonType(Type::Ice,Type::Psychic)),
        PokedexEntry(125, "Electabuzz", PokemonType(Type::Electric)),
        PokedexEntry(126, "Magmar", PokemonType(Type::Fire)),
        PokedexEntry(127, "Pinsir", PokemonType(Type::Bug)),
        PokedexEntry(128, "Tauros", PokemonType(Type::Normal)),
        PokedexEntry(129, "Magikarp", PokemonType(Type::Water)),
        PokedexEntry(130, "Gyarados", PokemonType(Type::Water,Type::Flying)),
        PokedexEntry(131, "Lapras", PokemonType(Type::Water,Type::Ice)),
        PokedexEntry(132, "Ditto", PokemonType(Type::Normal)),
        PokedexEntry(133, "Eevee", PokemonType(Type::Normal)),
        PokedexEntry(134, "Vaporean", PokemonType(Type::Water)),
        PokedexEntry(135, "Jolteon", PokemonType(Type::Electric)),
        PokedexEntry(136, "Flareon", PokemonType(Type::Fire)),
        PokedexEntry(137, "Porygon", PokemonType(Type::Normal)),
        PokedexEntry(138, "Omanyte", PokemonType(Type::Rock,Type::Water)),
        PokedexEntry(139, "Omastar", PokemonType(Type::Rock,Type::Water)),
        PokedexEntry(140, "Kabuto", PokemonType(Type::Rock,Type::Water)),
        PokedexEntry(141, "Kabutops", PokemonType(Type::Rock,Type::Water)),
        PokedexEntry(142, "Aerodactyl", PokemonType(Type::Rock,Type::Flying)),
        PokedexEntry(143, "Snorlax", PokemonType(Type::Normal)),
        PokedexEntry(144, "Articuno", PokemonType(Type::Ice,Type::Flying)),
        PokedexEntry(145, "Zapdos", PokemonType(Type::Electric,Type::Flying)),
        PokedexEntry(146, "Moltres", PokemonType(Type::Fire,Type::Flying)),
        PokedexEntry(147, "Dratini", PokemonType(Type::Dragon)),
        PokedexEntry(148, "Dragonair", PokemonType(Type::Dragon)),
        PokedexEntry(149, "Dragonite", PokemonType(Type::Dragon,Type::Flying)),
        PokedexEntry(150, "Mewtwo", PokemonType(Type::Psychic)),
        PokedexEntry(151, "Mew", PokemonType(Type::Psychic))
    };
};

#endif